// Code generated by cmd/settingsgen from contracts/settings/v1/manifest.json. DO NOT EDIT.
//
// Regenerate with: make settings-bindings
//
// Every key, type, scope and default here comes from the manifest, so a client
// cannot drift from the server's contract by editing a constant. Adding a setting
// is a manifest change plus a regeneration, never a hand-written key.

import Foundation

public struct SettingSuggestedOption: Hashable, Sendable {
    public let value: String
    public let introducedIn: Int
}

public struct SettingOptionSet: Hashable, Sendable {
    public let type: String
    public let options: [SettingSuggestedOption]
}

public struct SettingPresentation: Hashable, Sendable {
    public let suggestedOptions: String?
    public let unsetLabel: String?
}

/// Every setting the contract defines.
public enum SettingKey: String, CaseIterable, Sendable {
    /// Metadata language
    case catalogMetadataLanguage = "catalog.metadata_language"
    /// Metadata language exceptions
    case catalogMetadataLanguageOverrides = "catalog.metadata_language_overrides"
    /// Show advisory age
    case catalogShowAdvisoryAge = "catalog.show_advisory_age"
    /// Download quality
    case downloadsDefaultQuality = "downloads.default_quality"
    /// Keep watched downloads
    case downloadsKeepWatched = "downloads.keep_watched"
    /// Download over Wi-Fi only
    case downloadsWifiOnly = "downloads.wifi_only"
    /// Hide watched items from Home
    case homeHideWatchedItems = "home.hide_watched_items"
    /// Show adult titles in Featured
    case homeShowAdultInFeatured = "home.show_adult_in_featured"
    /// Primary menu
    case navPrimaryMenu = "nav.primary_menu"
    /// Navigation shortcuts
    case navShortcuts = "nav.shortcuts"
    /// Show audiobooks
    case navShowAudiobooks = "nav.show_audiobooks"
    /// Preferred audio language
    case playbackAudioLanguage = "playback.audio_language"
    /// Auto-play next episode
    case playbackAutoPlayNext = "playback.auto_play_next"
    /// Preview next episode
    case playbackAutoPlayNextPreview = "playback.auto_play_next_preview"
    /// Auto-skip credits
    case playbackAutoSkipCredits = "playback.auto_skip_credits"
    /// Auto-skip intros
    case playbackAutoSkipIntro = "playback.auto_skip_intro"
    /// Auto-skip recaps
    case playbackAutoSkipRecap = "playback.auto_skip_recap"
    /// Skip intros
    case playbackIntroSkipMode = "playback.intro_skip_mode"
    /// Maximum bitrate
    case playbackMaxBitrateKbps = "playback.max_bitrate_kbps"
    /// Next up prompt
    case playbackNextUpPromptSeconds = "playback.next_up_prompt_seconds"
    /// Preferred quality
    case playbackPreferredQuality = "playback.preferred_quality"
    /// Show forced subtitles
    case playbackShowForcedSubtitles = "playback.show_forced_subtitles"
    /// Subtitle appearance
    case playbackSubtitleAppearance = "playback.subtitle_appearance"
    /// Preferred subtitle language
    case playbackSubtitleLanguage = "playback.subtitle_language"
    /// Subtitles
    case playbackSubtitleMode = "playback.subtitle_mode"
    /// Audio sync offset
    case playerAudioSyncMs = "player.audio_sync_ms"
    /// Audiobook rewind interval
    case playerAudiobookSkipBackSeconds = "player.audiobook_skip_back_seconds"
    /// Audiobook fast-forward interval
    case playerAudiobookSkipForwardSeconds = "player.audiobook_skip_forward_seconds"
    /// Dolby Vision
    case playerDolbyVisionEnabled = "player.dolby_vision_enabled"
    /// Dolby Vision Profile 7 fallback
    case playerDvProfile7Hdr10Fallback = "player.dv_profile7_hdr10_fallback"
    /// HDR
    case playerHdrEnabled = "player.hdr_enabled"
    /// Match content frame rate
    case playerMatchFrameRate = "player.match_frame_rate"
    /// Screen orientation
    case playerOrientationMode = "player.orientation_mode"
    /// Still watching prompt
    case playerPassoutThreshold = "player.passout_threshold"
    /// Picture in picture
    case playerPictureInPictureEnabled = "player.picture_in_picture_enabled"
    /// Playback speed
    case playerPlaybackSpeed = "player.playback_speed"
    /// Rewind on resume
    case playerResumeRewindSeconds = "player.resume_rewind_seconds"
    /// Seek cache
    case playerSeekCacheEnabled = "player.seek_cache_enabled"
    /// Default sleep timer
    case playerSleepTimerDefaultMinutes = "player.sleep_timer_default_minutes"
    /// Subtitle sync offset
    case playerSubtitleSyncMs = "player.subtitle_sync_ms"
    /// Video sizing
    case playerVideoGravity = "player.video_gravity"
    /// Video rewind interval
    case playerVideoSkipBackSeconds = "player.video_skip_back_seconds"
    /// Video fast-forward interval
    case playerVideoSkipForwardSeconds = "player.video_skip_forward_seconds"
    /// Request titles I add to my watchlist
    case requestsWatchlistAutoRequest = "requests.watchlist_auto_request"
    /// Search scope
    case searchMediaScope = "search.media_scope"
    /// Match device caption settings
    case subtitleMatchesDevice = "subtitle.matches_device"
    /// Poster badges
    case uiCardOverlays = "ui.card_overlays"
    /// Card overlays enabled
    case uiCardOverlaysEnabled = "ui.card_overlays_enabled"
    /// Media cards
    case uiCardPresentation = "ui.card_presentation"
    /// Card quick actions
    case uiCardQuickActions = "ui.card_quick_actions"
    /// Card quick actions enabled
    case uiCardQuickActionsEnabled = "ui.card_quick_actions_enabled"
    /// Custom CSS
    case uiCustomCss = "ui.custom_css"
    /// Custom theme variables
    case uiCustomThemeVars = "ui.custom_theme_vars"
    /// Date format
    case uiDateFormat = "ui.date_format"
    /// Hidden libraries
    case uiDisabledLibraryIds = "ui.disabled_library_ids"
    /// High contrast
    case uiHighContrast = "ui.high_contrast"
    /// Library order
    case uiLibraryOrder = "ui.library_order"
    /// Remembered library view
    case uiLibraryPageState = "ui.library_page_state"
    /// Next up episodes
    case uiNextUpMode = "ui.next_up_mode"
    /// Remember library view
    case uiRememberLibraryPageState = "ui.remember_library_page_state"
    /// Pinned sidebar items
    case uiSidebarPins = "ui.sidebar_pins"
    /// Text size
    case uiTextScale = "ui.text_scale"
    /// Text weight
    case uiTextWeight = "ui.text_weight"
    /// Theme
    case uiTheme = "ui.theme"
    /// Theme music
    case uiThemeMusicEnabled = "ui.theme_music_enabled"
    /// Loop theme music
    case uiThemeMusicLoop = "ui.theme_music_loop"
    /// Time format
    case uiTimeFormat = "ui.time_format"
    /// Show title art
    case uiTitleArt = "ui.title_art"
}

public extension SettingKey {
    static let revision = 17

    /// Keys the server stores. The rest never leave the device.
    static let remote: [SettingKey] = [
        .catalogMetadataLanguage,
        .catalogMetadataLanguageOverrides,
        .catalogShowAdvisoryAge,
        .homeHideWatchedItems,
        .homeShowAdultInFeatured,
        .navPrimaryMenu,
        .navShortcuts,
        .playbackAudioLanguage,
        .playbackAutoPlayNext,
        .playbackAutoPlayNextPreview,
        .playbackAutoSkipCredits,
        .playbackAutoSkipIntro,
        .playbackAutoSkipRecap,
        .playbackIntroSkipMode,
        .playbackMaxBitrateKbps,
        .playbackNextUpPromptSeconds,
        .playbackPreferredQuality,
        .playbackShowForcedSubtitles,
        .playbackSubtitleAppearance,
        .playbackSubtitleLanguage,
        .playbackSubtitleMode,
        .playerAudioSyncMs,
        .playerAudiobookSkipBackSeconds,
        .playerAudiobookSkipForwardSeconds,
        .playerDolbyVisionEnabled,
        .playerDvProfile7Hdr10Fallback,
        .playerHdrEnabled,
        .playerMatchFrameRate,
        .playerOrientationMode,
        .playerPlaybackSpeed,
        .playerSeekCacheEnabled,
        .playerSleepTimerDefaultMinutes,
        .playerSubtitleSyncMs,
        .playerVideoGravity,
        .playerVideoSkipBackSeconds,
        .playerVideoSkipForwardSeconds,
        .requestsWatchlistAutoRequest,
        .searchMediaScope,
        .uiCardOverlays,
        .uiCardOverlaysEnabled,
        .uiCardPresentation,
        .uiCardQuickActions,
        .uiCardQuickActionsEnabled,
        .uiCustomCss,
        .uiCustomThemeVars,
        .uiDateFormat,
        .uiDisabledLibraryIds,
        .uiHighContrast,
        .uiLibraryOrder,
        .uiLibraryPageState,
        .uiNextUpMode,
        .uiRememberLibraryPageState,
        .uiSidebarPins,
        .uiTextScale,
        .uiTextWeight,
        .uiTheme,
        .uiThemeMusicEnabled,
        .uiThemeMusicLoop,
        .uiTimeFormat,
        .uiTitleArt,
    ]

    static let clientLocal: [SettingKey] = [
        .downloadsDefaultQuality,
        .downloadsKeepWatched,
        .downloadsWifiOnly,
        .navShowAudiobooks,
        .playerPassoutThreshold,
        .playerPictureInPictureEnabled,
        .playerResumeRewindSeconds,
        .subtitleMatchesDevice,
    ]

    /// Keys another definition supersedes. Still readable, never offered as
    /// a second control beside their replacement: the server mirrors the pair
    /// at write time, so editing either would rewrite the other.
    static let deprecated: Set<SettingKey> = [
        .playbackAutoSkipIntro,
        .uiCustomCss,
        .uiCustomThemeVars,
        .uiTheme,
    ]
}

public enum SettingPresentationMetadata {
    public static let optionSets: [String: SettingOptionSet] = [
        "catalog_metadata_languages": SettingOptionSet(
            type: "language_tag",
            options: [
                SettingSuggestedOption(value: "ar", introducedIn: 1),
                SettingSuggestedOption(value: "bn", introducedIn: 1),
                SettingSuggestedOption(value: "bg", introducedIn: 1),
                SettingSuggestedOption(value: "zh", introducedIn: 1),
                SettingSuggestedOption(value: "zh-Hans", introducedIn: 8),
                SettingSuggestedOption(value: "zh-Hant", introducedIn: 8),
                SettingSuggestedOption(value: "hr", introducedIn: 1),
                SettingSuggestedOption(value: "cs", introducedIn: 1),
                SettingSuggestedOption(value: "da", introducedIn: 1),
                SettingSuggestedOption(value: "nl", introducedIn: 1),
                SettingSuggestedOption(value: "en", introducedIn: 1),
                SettingSuggestedOption(value: "en-US", introducedIn: 8),
                SettingSuggestedOption(value: "en-GB", introducedIn: 8),
                SettingSuggestedOption(value: "fi", introducedIn: 1),
                SettingSuggestedOption(value: "fr", introducedIn: 1),
                SettingSuggestedOption(value: "fr-CA", introducedIn: 8),
                SettingSuggestedOption(value: "de", introducedIn: 1),
                SettingSuggestedOption(value: "el", introducedIn: 1),
                SettingSuggestedOption(value: "he", introducedIn: 1),
                SettingSuggestedOption(value: "hi", introducedIn: 1),
                SettingSuggestedOption(value: "hu", introducedIn: 1),
                SettingSuggestedOption(value: "id", introducedIn: 1),
                SettingSuggestedOption(value: "it", introducedIn: 1),
                SettingSuggestedOption(value: "ja", introducedIn: 1),
                SettingSuggestedOption(value: "ko", introducedIn: 1),
                SettingSuggestedOption(value: "ms", introducedIn: 1),
                SettingSuggestedOption(value: "no", introducedIn: 1),
                SettingSuggestedOption(value: "fa", introducedIn: 1),
                SettingSuggestedOption(value: "pl", introducedIn: 1),
                SettingSuggestedOption(value: "pt", introducedIn: 1),
                SettingSuggestedOption(value: "pt-BR", introducedIn: 8),
                SettingSuggestedOption(value: "pt-PT", introducedIn: 8),
                SettingSuggestedOption(value: "ro", introducedIn: 1),
                SettingSuggestedOption(value: "ru", introducedIn: 1),
                SettingSuggestedOption(value: "sk", introducedIn: 1),
                SettingSuggestedOption(value: "sl", introducedIn: 1),
                SettingSuggestedOption(value: "es", introducedIn: 1),
                SettingSuggestedOption(value: "es-419", introducedIn: 8),
                SettingSuggestedOption(value: "es-ES", introducedIn: 8),
                SettingSuggestedOption(value: "sv", introducedIn: 1),
                SettingSuggestedOption(value: "ta", introducedIn: 1),
                SettingSuggestedOption(value: "te", introducedIn: 1),
                SettingSuggestedOption(value: "th", introducedIn: 1),
                SettingSuggestedOption(value: "tr", introducedIn: 1),
                SettingSuggestedOption(value: "uk", introducedIn: 1),
                SettingSuggestedOption(value: "vi", introducedIn: 1),
            ]
        ),
        "playback_audio_languages": SettingOptionSet(
            type: "language_tag",
            options: [
                SettingSuggestedOption(value: "ar", introducedIn: 1),
                SettingSuggestedOption(value: "bn", introducedIn: 1),
                SettingSuggestedOption(value: "bg", introducedIn: 1),
                SettingSuggestedOption(value: "zh", introducedIn: 1),
                SettingSuggestedOption(value: "zh-Hans", introducedIn: 8),
                SettingSuggestedOption(value: "zh-Hant", introducedIn: 8),
                SettingSuggestedOption(value: "hr", introducedIn: 1),
                SettingSuggestedOption(value: "cs", introducedIn: 1),
                SettingSuggestedOption(value: "da", introducedIn: 1),
                SettingSuggestedOption(value: "nl", introducedIn: 1),
                SettingSuggestedOption(value: "en", introducedIn: 1),
                SettingSuggestedOption(value: "en-US", introducedIn: 8),
                SettingSuggestedOption(value: "en-GB", introducedIn: 8),
                SettingSuggestedOption(value: "fi", introducedIn: 1),
                SettingSuggestedOption(value: "fr", introducedIn: 1),
                SettingSuggestedOption(value: "fr-CA", introducedIn: 8),
                SettingSuggestedOption(value: "de", introducedIn: 1),
                SettingSuggestedOption(value: "el", introducedIn: 1),
                SettingSuggestedOption(value: "he", introducedIn: 1),
                SettingSuggestedOption(value: "hi", introducedIn: 1),
                SettingSuggestedOption(value: "hu", introducedIn: 1),
                SettingSuggestedOption(value: "id", introducedIn: 1),
                SettingSuggestedOption(value: "it", introducedIn: 1),
                SettingSuggestedOption(value: "ja", introducedIn: 1),
                SettingSuggestedOption(value: "ko", introducedIn: 1),
                SettingSuggestedOption(value: "ms", introducedIn: 1),
                SettingSuggestedOption(value: "no", introducedIn: 1),
                SettingSuggestedOption(value: "fa", introducedIn: 1),
                SettingSuggestedOption(value: "pl", introducedIn: 1),
                SettingSuggestedOption(value: "pt", introducedIn: 1),
                SettingSuggestedOption(value: "pt-BR", introducedIn: 8),
                SettingSuggestedOption(value: "pt-PT", introducedIn: 8),
                SettingSuggestedOption(value: "ro", introducedIn: 1),
                SettingSuggestedOption(value: "ru", introducedIn: 1),
                SettingSuggestedOption(value: "sk", introducedIn: 1),
                SettingSuggestedOption(value: "sl", introducedIn: 1),
                SettingSuggestedOption(value: "es", introducedIn: 1),
                SettingSuggestedOption(value: "es-419", introducedIn: 8),
                SettingSuggestedOption(value: "es-ES", introducedIn: 8),
                SettingSuggestedOption(value: "sv", introducedIn: 1),
                SettingSuggestedOption(value: "ta", introducedIn: 1),
                SettingSuggestedOption(value: "te", introducedIn: 1),
                SettingSuggestedOption(value: "th", introducedIn: 1),
                SettingSuggestedOption(value: "tr", introducedIn: 1),
                SettingSuggestedOption(value: "uk", introducedIn: 1),
                SettingSuggestedOption(value: "vi", introducedIn: 1),
            ]
        ),
        "playback_subtitle_languages": SettingOptionSet(
            type: "language_tag",
            options: [
                SettingSuggestedOption(value: "ar", introducedIn: 1),
                SettingSuggestedOption(value: "bn", introducedIn: 1),
                SettingSuggestedOption(value: "bg", introducedIn: 1),
                SettingSuggestedOption(value: "zh", introducedIn: 1),
                SettingSuggestedOption(value: "zh-Hans", introducedIn: 8),
                SettingSuggestedOption(value: "zh-Hant", introducedIn: 8),
                SettingSuggestedOption(value: "hr", introducedIn: 1),
                SettingSuggestedOption(value: "cs", introducedIn: 1),
                SettingSuggestedOption(value: "da", introducedIn: 1),
                SettingSuggestedOption(value: "nl", introducedIn: 1),
                SettingSuggestedOption(value: "en", introducedIn: 1),
                SettingSuggestedOption(value: "en-US", introducedIn: 8),
                SettingSuggestedOption(value: "en-GB", introducedIn: 8),
                SettingSuggestedOption(value: "fi", introducedIn: 1),
                SettingSuggestedOption(value: "fr", introducedIn: 1),
                SettingSuggestedOption(value: "fr-CA", introducedIn: 8),
                SettingSuggestedOption(value: "de", introducedIn: 1),
                SettingSuggestedOption(value: "el", introducedIn: 1),
                SettingSuggestedOption(value: "he", introducedIn: 1),
                SettingSuggestedOption(value: "hi", introducedIn: 1),
                SettingSuggestedOption(value: "hu", introducedIn: 1),
                SettingSuggestedOption(value: "id", introducedIn: 1),
                SettingSuggestedOption(value: "it", introducedIn: 1),
                SettingSuggestedOption(value: "ja", introducedIn: 1),
                SettingSuggestedOption(value: "ko", introducedIn: 1),
                SettingSuggestedOption(value: "ms", introducedIn: 1),
                SettingSuggestedOption(value: "no", introducedIn: 1),
                SettingSuggestedOption(value: "fa", introducedIn: 1),
                SettingSuggestedOption(value: "pl", introducedIn: 1),
                SettingSuggestedOption(value: "pt", introducedIn: 1),
                SettingSuggestedOption(value: "pt-BR", introducedIn: 8),
                SettingSuggestedOption(value: "pt-PT", introducedIn: 8),
                SettingSuggestedOption(value: "ro", introducedIn: 1),
                SettingSuggestedOption(value: "ru", introducedIn: 1),
                SettingSuggestedOption(value: "sk", introducedIn: 1),
                SettingSuggestedOption(value: "sl", introducedIn: 1),
                SettingSuggestedOption(value: "es", introducedIn: 1),
                SettingSuggestedOption(value: "es-419", introducedIn: 8),
                SettingSuggestedOption(value: "es-ES", introducedIn: 8),
                SettingSuggestedOption(value: "sv", introducedIn: 1),
                SettingSuggestedOption(value: "ta", introducedIn: 1),
                SettingSuggestedOption(value: "te", introducedIn: 1),
                SettingSuggestedOption(value: "th", introducedIn: 1),
                SettingSuggestedOption(value: "tr", introducedIn: 1),
                SettingSuggestedOption(value: "uk", introducedIn: 1),
                SettingSuggestedOption(value: "vi", introducedIn: 1),
            ]
        ),
    ]

    public static let definitions: [SettingKey: SettingPresentation] = [
        .catalogMetadataLanguage: SettingPresentation(
            suggestedOptions: "catalog_metadata_languages",
            unsetLabel: "Library default"
        ),
        .playbackAudioLanguage: SettingPresentation(
            suggestedOptions: "playback_audio_languages",
            unsetLabel: "No preference"
        ),
        .playbackSubtitleLanguage: SettingPresentation(
            suggestedOptions: "playback_subtitle_languages",
            unsetLabel: "None"
        ),
    ]

    public static func suggestedValues(
        for key: SettingKey,
        revision: Int = SettingKey.revision
    ) -> [String] {
        guard let setID = definitions[key]?.suggestedOptions,
              let optionSet = optionSets[setID] else { return [] }
        return optionSet.options
            .filter { $0.introducedIn <= revision }
            .map(\.value)
    }
}
